INSERT INTO galletas (nombre, cantidad, precio, descripcion) VALUES
('Galleta de Fresa', 4, 2.21, 'Sabor caramelo, textura crujiente.'),
('Galleta de Doble Chocolate', 5, 2.48, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Fresa', 8, 4.68, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Canela', 2, 1.12, 'Sabor jengibre, textura crujiente.'),
('Galleta de Naranja', 3, 3.66, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Canela', 8, 2.89, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Jengibre', 7, 1.07, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Mantequilla', 5, 1.22, 'Sabor avena, textura crujiente.'),
('Galleta de Vainilla', 10, 3.49, 'Sabor avena, textura crujiente.'),
('Galleta de Mantequilla', 4, 3.43, 'Sabor miel, textura crujiente.'),
('Galleta de Naranja', 3, 2.45, 'Sabor caramelo, textura crujiente.'),
('Galleta de Jengibre', 2, 1.22, 'Sabor fresa, textura suave.'),
('Galleta de Miel', 10, 3.07, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Mantequilla', 5, 4.77, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Vainilla', 2, 3.02, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Miel', 10, 2.62, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 4, 3.77, 'Sabor naranja, textura crujiente.'),
('Galleta de Coco', 7, 3.4, 'Sabor chocolate, textura crujiente.'),
('Galleta de Avena', 3, 2.13, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Canela', 6, 3.45, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Chocolate', 6, 2.61, 'Sabor miel, textura crujiente.'),
('Galleta de Avena', 2, 2.17, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Fresa', 4, 3.78, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 5, 2.25, 'Sabor jengibre, textura crujiente.'),
('Galleta de Chocolate', 10, 3.73, 'Sabor caramelo, textura crujiente.'),
('Galleta de Fresa', 6, 4.54, 'Sabor naranja, textura crujiente.'),
('Galleta de Miel', 1, 4.96, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 4, 4.67, 'Sabor jengibre, textura crujiente.'),
('Galleta de Coco', 2, 4.05, 'Sabor chocolate, textura crujiente.'),
('Galleta de Miel', 3, 3.61, 'Sabor jengibre, textura crujiente.'),
('Galleta de Fresa', 5, 2.5, 'Sabor naranja, textura crujiente.'),
('Galleta de Naranja', 4, 3.13, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 2, 1.12, 'Sabor fresa, textura suave.'),
('Galleta de Canela', 5, 1.51, 'Sabor avena, textura crujiente.'),
('Galleta de Chocolate', 2, 1.34, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Mantequilla', 7, 1.65, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Fresa', 4, 2.58, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 6, 1.71, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Mantequilla', 2, 3.33, 'Sabor jengibre, textura crujiente.'),
('Galleta de Naranja', 7, 3.69, 'Sabor chocolate, textura crujiente.'),
('Galleta de Avena', 1, 1.41, 'Sabor caramelo, textura crujiente.'),
('Galleta de Chocolate', 7, 1.29, 'Sabor naranja, textura crujiente.'),
('Galleta de Jengibre', 5, 4.4, 'Sabor miel, textura crujiente.'),
('Galleta de Miel', 4, 3.68, 'Sabor fresa, textura suave.'),
('Galleta de Jengibre', 7, 3.22, 'Sabor naranja, textura crujiente.'),
('Galleta de Canela', 10, 3.23, 'Sabor fresa, textura suave.'),
('Galleta de Avena', 5, 2.22, 'Sabor canela, textura crujiente.'),
('Galleta de Naranja', 8, 3.46, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 5, 4.73, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 10, 3.76, 'Sabor miel, textura crujiente.'),
('Galleta de Fresa', 1, 4.79, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Jengibre', 7, 1.21, 'Sabor canela, textura crujiente.'),
('Galleta de Mantequilla', 1, 2.2, 'Sabor chocolate, textura crujiente.'),
('Galleta de Caramelo', 7, 4.67, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Jengibre', 1, 4.36, 'Sabor chocolate, textura crujiente.'),
('Galleta de Miel', 1, 4.53, 'Sabor jengibre, textura crujiente.'),
('Galleta de Doble Chocolate', 6, 4.99, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 9, 1.06, 'Sabor avena, textura crujiente.'),
('Galleta de Mantequilla', 5, 3.3, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 9, 2.25, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 4, 3.95, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 3, 4.68, 'Sabor coco, textura crujiente.'),
('Galleta de Vainilla', 2, 1.2, 'Sabor naranja, textura crujiente.'),
('Galleta de Mantequilla', 3, 4.49, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Canela', 3, 1.02, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Mantequilla', 4, 2.84, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 8, 1.05, 'Sabor caramelo, textura crujiente.'),
('Galleta de Fresa', 6, 1.91, 'Sabor avena, textura crujiente.'),
('Galleta de Coco', 4, 4.71, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 10, 4.59, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 5, 4.07, 'Sabor caramelo, textura crujiente.'),
('Galleta de Chocolate', 6, 1.72, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 3, 4.37, 'Sabor caramelo, textura crujiente.'),
('Galleta de Caramelo', 10, 4.6, 'Sabor jengibre, textura crujiente.'),
('Galleta de Canela', 4, 5.0, 'Sabor chocolate, textura crujiente.'),
('Galleta de Coco', 7, 3.65, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 6, 1.1, 'Sabor caramelo, textura crujiente.'),
('Galleta de Doble Chocolate', 1, 4.61, 'Sabor miel, textura crujiente.'),
('Galleta de Vainilla', 10, 2.25, 'Sabor fresa, textura suave.'),
('Galleta de Mantequilla', 3, 4.75, 'Sabor canela, textura crujiente.'),
('Galleta de Mantequilla', 10, 1.29, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Caramelo', 9, 4.74, 'Sabor miel, textura crujiente.'),
('Galleta de Miel', 3, 4.89, 'Sabor chocolate, textura crujiente.'),
('Galleta de Vainilla', 3, 3.73, 'Sabor naranja, textura crujiente.'),
('Galleta de Canela', 1, 3.73, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Fresa', 5, 4.04, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 9, 2.73, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Mantequilla', 5, 4.7, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 4, 3.43, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 6, 2.7, 'Sabor canela, textura crujiente.'),
('Galleta de Naranja', 4, 4.58, 'Sabor jengibre, textura crujiente.'),
('Galleta de Vainilla', 1, 4.71, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Chocolate', 8, 3.12, 'Sabor canela, textura crujiente.'),
('Galleta de Canela', 9, 1.81, 'Sabor coco, textura crujiente.'),
('Galleta de Vainilla', 2, 3.62, 'Sabor jengibre, textura crujiente.'),
('Galleta de Caramelo', 7, 2.21, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 9, 2.57, 'Sabor canela, textura crujiente.'),
('Galleta de Doble Chocolate', 8, 2.85, 'Sabor jengibre, textura crujiente.'),
('Galleta de Avena', 9, 1.02, 'Sabor fresa, textura suave.'),
('Galleta de Canela', 5, 1.33, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 10, 1.92, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 6, 1.82, 'Sabor canela, textura crujiente.'),
('Galleta de Mantequilla', 6, 1.36, 'Sabor coco, textura crujiente.'),
('Galleta de Miel', 4, 3.41, 'Sabor chocolate, textura crujiente.'),
('Galleta de Naranja', 10, 1.85, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Fresa', 6, 4.05, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 8, 3.97, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Coco', 8, 3.94, 'Sabor avena, textura crujiente.'),
('Galleta de Avena', 5, 1.53, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 10, 4.28, 'Sabor chocolate, textura crujiente.'),
('Galleta de Canela', 7, 3.03, 'Sabor fresa, textura suave.'),
('Galleta de Mantequilla', 3, 3.12, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Chocolate', 4, 4.46, 'Sabor coco, textura crujiente.'),
('Galleta de Vainilla', 6, 3.81, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 10, 3.55, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Chocolate', 10, 5.0, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Fresa', 7, 4.65, 'Sabor chocolate, textura crujiente.'),
('Galleta de Jengibre', 6, 1.67, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 1, 2.13, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 3, 2.75, 'Sabor miel, textura crujiente.'),
('Galleta de Canela', 8, 1.24, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Doble Chocolate', 8, 4.2, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 2, 2.69, 'Sabor coco, textura crujiente.'),
('Galleta de Coco', 1, 3.8, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Avena', 3, 2.29, 'Sabor jengibre, textura crujiente.'),
('Galleta de Avena', 9, 1.99, 'Sabor canela, textura crujiente.'),
('Galleta de Miel', 6, 4.62, 'Sabor fresa, textura suave.'),
('Galleta de Mantequilla', 10, 1.87, 'Sabor naranja, textura crujiente.'),
('Galleta de Fresa', 10, 1.31, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 9, 2.24, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Doble Chocolate', 9, 4.72, 'Sabor naranja, textura crujiente.'),
('Galleta de Fresa', 4, 2.36, 'Sabor avena, textura crujiente.'),
('Galleta de Vainilla', 1, 1.08, 'Sabor naranja, textura crujiente.'),
('Galleta de Jengibre', 1, 3.14, 'Sabor naranja, textura crujiente.'),
('Galleta de Caramelo', 6, 2.34, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 1, 3.77, 'Sabor canela, textura crujiente.'),
('Galleta de Fresa', 7, 4.35, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 1, 1.08, 'Sabor chocolate, textura crujiente.'),
('Galleta de Avena', 7, 4.87, 'Sabor jengibre, textura crujiente.'),
('Galleta de Canela', 4, 3.19, 'Sabor chocolate, textura crujiente.'),
('Galleta de Coco', 7, 2.66, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 7, 3.0, 'Sabor canela, textura crujiente.'),
('Galleta de Avena', 10, 1.87, 'Sabor jengibre, textura crujiente.'),
('Galleta de Mantequilla', 7, 2.76, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Miel', 4, 1.49, 'Sabor naranja, textura crujiente.'),
('Galleta de Doble Chocolate', 8, 4.17, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Jengibre', 8, 4.06, 'Sabor naranja, textura crujiente.'),
('Galleta de Coco', 6, 2.04, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 1, 3.74, 'Sabor miel, textura crujiente.'),
('Galleta de Doble Chocolate', 2, 3.6, 'Sabor fresa, textura suave.'),
('Galleta de Vainilla', 5, 2.83, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 6, 1.32, 'Sabor avena, textura crujiente.'),
('Galleta de Mantequilla', 3, 4.28, 'Sabor jengibre, textura crujiente.'),
('Galleta de Vainilla', 2, 1.23, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Coco', 1, 2.76, 'Sabor canela, textura crujiente.'),
('Galleta de Avena', 6, 4.44, 'Sabor caramelo, textura crujiente.'),
('Galleta de Avena', 4, 2.56, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 1, 1.32, 'Sabor canela, textura crujiente.'),
('Galleta de Fresa', 3, 3.7, 'Sabor jengibre, textura crujiente.'),
('Galleta de Coco', 5, 2.14, 'Sabor naranja, textura crujiente.'),
('Galleta de Doble Chocolate', 2, 4.85, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Mantequilla', 8, 1.82, 'Sabor canela, textura crujiente.'),
('Galleta de Caramelo', 5, 3.37, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 6, 4.55, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 10, 3.79, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 5, 4.4, 'Sabor chocolate, textura crujiente.'),
('Galleta de Caramelo', 8, 3.63, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Canela', 6, 3.17, 'Sabor avena, textura crujiente.'),
('Galleta de Canela', 4, 4.8, 'Sabor jengibre, textura crujiente.'),
('Galleta de Naranja', 2, 2.53, 'Sabor fresa, textura suave.'),
('Galleta de Coco', 2, 2.61, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 7, 1.55, 'Sabor jengibre, textura crujiente.'),
('Galleta de Miel', 5, 3.54, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 4, 2.66, 'Sabor jengibre, textura crujiente.'),
('Galleta de Fresa', 5, 1.26, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Vainilla', 1, 1.99, 'Sabor chocolate, textura crujiente.'),
('Galleta de Fresa', 5, 1.27, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Canela', 10, 4.01, 'Sabor coco, textura crujiente.'),
('Galleta de Jengibre', 10, 1.52, 'Sabor chocolate, textura crujiente.'),
('Galleta de Caramelo', 3, 2.85, 'Sabor chocolate, textura crujiente.'),
('Galleta de Naranja', 6, 3.0, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 2, 2.14, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 9, 2.05, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 8, 3.18, 'Sabor coco, textura crujiente.'),
('Galleta de Fresa', 9, 4.8, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 5, 3.37, 'Sabor chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 8, 4.81, 'Sabor canela, textura crujiente.'),
('Galleta de Doble Chocolate', 5, 3.45, 'Sabor jengibre, textura crujiente.'),
('Galleta de Avena', 10, 4.64, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Canela', 2, 2.63, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 8, 2.22, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Fresa', 8, 1.8, 'Sabor jengibre, textura crujiente.'),
('Galleta de Mantequilla', 7, 1.89, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 4, 3.75, 'Sabor fresa, textura suave.'),
('Galleta de Naranja', 8, 1.49, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Fresa', 2, 1.36, 'Sabor naranja, textura crujiente.'),
('Galleta de Caramelo', 3, 4.81, 'Sabor avena, textura crujiente.'),
('Galleta de Fresa', 7, 2.19, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 4, 3.55, 'Sabor chocolate, textura crujiente.'),
('Galleta de Fresa', 6, 2.82, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Naranja', 1, 1.1, 'Sabor naranja, textura crujiente.'),
('Galleta de Coco', 10, 2.85, 'Sabor avena, textura crujiente.'),
('Galleta de Doble Chocolate', 7, 3.06, 'Sabor caramelo, textura crujiente.'),
('Galleta de Canela', 3, 1.73, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 4, 3.3, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Avena', 9, 1.54, 'Sabor naranja, textura crujiente.'),
('Galleta de Fresa', 3, 2.16, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Jengibre', 8, 4.66, 'Sabor jengibre, textura crujiente.'),
('Galleta de Miel', 2, 3.49, 'Sabor naranja, textura crujiente.'),
('Galleta de Jengibre', 4, 4.03, 'Sabor naranja, textura crujiente.'),
('Galleta de Chocolate', 7, 3.82, 'Sabor fresa, textura suave.'),
('Galleta de Naranja', 7, 4.36, 'Sabor avena, textura crujiente.'),
('Galleta de Coco', 7, 3.57, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Miel', 6, 4.69, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Caramelo', 7, 1.93, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Jengibre', 2, 3.38, 'Sabor chocolate, textura crujiente.'),
('Galleta de Mantequilla', 7, 3.08, 'Sabor miel, textura crujiente.'),
('Galleta de Fresa', 5, 1.06, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Miel', 6, 2.51, 'Sabor avena, textura crujiente.'),
('Galleta de Canela', 1, 3.74, 'Sabor coco, textura crujiente.'),
('Galleta de Canela', 8, 4.78, 'Sabor chocolate, textura crujiente.'),
('Galleta de Canela', 8, 1.48, 'Sabor miel, textura crujiente.'),
('Galleta de Chocolate', 4, 4.01, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 6, 3.51, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 8, 1.66, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Jengibre', 8, 3.53, 'Sabor avena, textura crujiente.'),
('Galleta de Caramelo', 4, 4.42, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Coco', 3, 3.58, 'Sabor naranja, textura crujiente.'),
('Galleta de Fresa', 10, 3.08, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Mantequilla', 9, 1.09, 'Sabor caramelo, textura crujiente.'),
('Galleta de Coco', 10, 3.14, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 6, 1.51, 'Sabor avena, textura crujiente.'),
('Galleta de Chocolate', 10, 2.67, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Canela', 7, 1.54, 'Sabor miel, textura crujiente.'),
('Galleta de Miel', 1, 4.22, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Miel', 9, 4.9, 'Sabor naranja, textura crujiente.'),
('Galleta de Mantequilla', 9, 4.31, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 2, 3.19, 'Sabor jengibre, textura crujiente.'),
('Galleta de Doble Chocolate', 4, 4.52, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 8, 2.42, 'Sabor naranja, textura crujiente.'),
('Galleta de Coco', 6, 2.38, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Mantequilla', 8, 3.42, 'Sabor naranja, textura crujiente.'),
('Galleta de Mantequilla', 8, 2.11, 'Sabor naranja, textura crujiente.'),
('Galleta de Miel', 1, 1.38, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 4, 2.85, 'Sabor caramelo, textura crujiente.'),
('Galleta de Mantequilla', 7, 1.15, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 10, 2.74, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 9, 2.21, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Chocolate', 2, 3.76, 'Sabor jengibre, textura crujiente.'),
('Galleta de Doble Chocolate', 9, 2.43, 'Sabor jengibre, textura crujiente.'),
('Galleta de Mantequilla', 2, 4.1, 'Sabor jengibre, textura crujiente.'),
('Galleta de Coco', 1, 3.12, 'Sabor miel, textura crujiente.'),
('Galleta de Canela', 3, 3.88, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 3, 4.0, 'Sabor canela, textura crujiente.'),
('Galleta de Fresa', 10, 2.1, 'Sabor avena, textura crujiente.'),
('Galleta de Chocolate', 6, 3.23, 'Sabor naranja, textura crujiente.'),
('Galleta de Caramelo', 1, 1.8, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 1, 4.39, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 8, 2.0, 'Sabor caramelo, textura crujiente.'),
('Galleta de Fresa', 6, 3.94, 'Sabor canela, textura crujiente.'),
('Galleta de Avena', 6, 3.34, 'Sabor jengibre, textura crujiente.'),
('Galleta de Chocolate', 1, 3.35, 'Sabor fresa, textura suave.'),
('Galleta de Naranja', 3, 1.67, 'Sabor naranja, textura crujiente.'),
('Galleta de Canela', 5, 2.92, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 5, 3.28, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Doble Chocolate', 6, 4.45, 'Sabor fresa, textura suave.'),
('Galleta de Doble Chocolate', 10, 4.08, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 7, 3.36, 'Sabor naranja, textura crujiente.'),
('Galleta de Naranja', 3, 2.38, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 9, 1.65, 'Sabor canela, textura crujiente.'),
('Galleta de Mantequilla', 6, 4.87, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Chocolate', 7, 2.18, 'Sabor canela, textura crujiente.'),
('Galleta de Mantequilla', 2, 2.87, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Mantequilla', 3, 3.15, 'Sabor miel, textura crujiente.'),
('Galleta de Jengibre', 2, 4.74, 'Sabor canela, textura crujiente.'),
('Galleta de Jengibre', 5, 2.22, 'Sabor chocolate, textura crujiente.'),
('Galleta de Mantequilla', 3, 3.11, 'Sabor naranja, textura crujiente.'),
('Galleta de Doble Chocolate', 9, 4.36, 'Sabor coco, textura crujiente.'),
('Galleta de Coco', 8, 1.72, 'Sabor caramelo, textura crujiente.'),
('Galleta de Doble Chocolate', 7, 3.87, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Vainilla', 4, 4.38, 'Sabor caramelo, textura crujiente.'),
('Galleta de Coco', 6, 3.44, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 3, 2.43, 'Sabor chocolate, textura crujiente.'),
('Galleta de Avena', 10, 4.93, 'Sabor jengibre, textura crujiente.'),
('Galleta de Fresa', 5, 2.74, 'Sabor jengibre, textura crujiente.'),
('Galleta de Coco', 2, 4.77, 'Sabor jengibre, textura crujiente.'),
('Galleta de Canela', 1, 3.25, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 6, 1.38, 'Sabor jengibre, textura crujiente.'),
('Galleta de Coco', 9, 2.58, 'Sabor jengibre, textura crujiente.'),
('Galleta de Doble Chocolate', 3, 1.85, 'Sabor chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 6, 1.15, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Avena', 3, 1.34, 'Sabor jengibre, textura crujiente.'),
('Galleta de Caramelo', 8, 4.46, 'Sabor fresa, textura suave.'),
('Galleta de Canela', 1, 2.33, 'Sabor chocolate, textura crujiente.'),
('Galleta de Jengibre', 7, 4.94, 'Sabor coco, textura crujiente.'),
('Galleta de Miel', 3, 4.1, 'Sabor avena, textura crujiente.'),
('Galleta de Jengibre', 9, 2.67, 'Sabor miel, textura crujiente.'),
('Galleta de Canela', 5, 1.75, 'Sabor miel, textura crujiente.'),
('Galleta de Avena', 1, 4.6, 'Sabor naranja, textura crujiente.'),
('Galleta de Jengibre', 2, 2.24, 'Sabor miel, textura crujiente.'),
('Galleta de Fresa', 2, 2.37, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 8, 4.48, 'Sabor fresa, textura suave.'),
('Galleta de Miel', 1, 3.27, 'Sabor coco, textura crujiente.'),
('Galleta de Mantequilla', 10, 2.11, 'Sabor caramelo, textura crujiente.'),
('Galleta de Naranja', 1, 2.53, 'Sabor coco, textura crujiente.'),
('Galleta de Avena', 8, 1.47, 'Sabor caramelo, textura crujiente.'),
('Galleta de Coco', 9, 4.18, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 7, 2.33, 'Sabor jengibre, textura crujiente.'),
('Galleta de Jengibre', 3, 2.0, 'Sabor canela, textura crujiente.'),
('Galleta de Vainilla', 4, 1.64, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 6, 4.66, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 4, 3.37, 'Sabor jengibre, textura crujiente.'),
('Galleta de Doble Chocolate', 7, 2.47, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 3, 1.91, 'Sabor caramelo, textura crujiente.'),
('Galleta de Miel', 4, 1.09, 'Sabor canela, textura crujiente.'),
('Galleta de Naranja', 8, 2.99, 'Sabor fresa, textura suave.'),
('Galleta de Jengibre', 6, 1.54, 'Sabor avena, textura crujiente.'),
('Galleta de Avena', 5, 3.23, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Canela', 5, 1.32, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 1, 2.07, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 10, 4.42, 'Sabor naranja, textura crujiente.'),
('Galleta de Vainilla', 10, 2.13, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 7, 2.27, 'Sabor fresa, textura suave.'),
('Galleta de Canela', 7, 4.95, 'Sabor chocolate, textura crujiente.'),
('Galleta de Vainilla', 2, 2.44, 'Sabor fresa, textura suave.'),
('Galleta de Miel', 2, 4.26, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 5, 2.75, 'Sabor chocolate, textura crujiente.'),
('Galleta de Naranja', 5, 4.29, 'Sabor coco, textura crujiente.'),
('Galleta de Jengibre', 8, 1.11, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Caramelo', 2, 1.71, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 7, 1.83, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 2, 3.09, 'Sabor naranja, textura crujiente.'),
('Galleta de Canela', 2, 1.12, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Avena', 3, 3.01, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 10, 2.91, 'Sabor coco, textura crujiente.'),
('Galleta de Naranja', 6, 4.15, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 1, 3.12, 'Sabor jengibre, textura crujiente.'),
('Galleta de Avena', 3, 3.29, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Coco', 6, 2.2, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Coco', 7, 4.76, 'Sabor miel, textura crujiente.'),
('Galleta de Fresa', 9, 1.4, 'Sabor miel, textura crujiente.'),
('Galleta de Jengibre', 8, 4.22, 'Sabor caramelo, textura crujiente.'),
('Galleta de Avena', 2, 1.69, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 8, 3.06, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 5, 2.78, 'Sabor coco, textura crujiente.'),
('Galleta de Coco', 9, 3.3, 'Sabor naranja, textura crujiente.'),
('Galleta de Canela', 7, 1.26, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Chocolate', 1, 3.24, 'Sabor naranja, textura crujiente.'),
('Galleta de Chocolate', 4, 2.3, 'Sabor chocolate, textura crujiente.'),
('Galleta de Coco', 1, 2.93, 'Sabor coco, textura crujiente.'),
('Galleta de Fresa', 7, 3.22, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 2, 3.94, 'Sabor fresa, textura suave.'),
('Galleta de Vainilla', 7, 4.97, 'Sabor caramelo, textura crujiente.'),
('Galleta de Avena', 8, 1.73, 'Sabor chocolate, textura crujiente.'),
('Galleta de Miel', 2, 4.57, 'Sabor canela, textura crujiente.'),
('Galleta de Chocolate', 9, 4.64, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 8, 4.05, 'Sabor miel, textura crujiente.'),
('Galleta de Avena', 6, 2.1, 'Sabor canela, textura crujiente.'),
('Galleta de Doble Chocolate', 3, 4.13, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 2, 1.39, 'Sabor avena, textura crujiente.'),
('Galleta de Jengibre', 5, 4.19, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Naranja', 10, 4.59, 'Sabor naranja, textura crujiente.'),
('Galleta de Caramelo', 6, 4.54, 'Sabor coco, textura crujiente.'),
('Galleta de Chocolate', 5, 2.31, 'Sabor avena, textura crujiente.'),
('Galleta de Canela', 6, 2.05, 'Sabor chocolate, textura crujiente.'),
('Galleta de Jengibre', 4, 1.65, 'Sabor canela, textura crujiente.'),
('Galleta de Caramelo', 2, 3.09, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 5, 1.81, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 7, 4.04, 'Sabor jengibre, textura crujiente.'),
('Galleta de Naranja', 5, 2.73, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Chocolate', 8, 2.99, 'Sabor chocolate, textura crujiente.'),
('Galleta de Canela', 6, 4.09, 'Sabor miel, textura crujiente.'),
('Galleta de Doble Chocolate', 3, 2.66, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Fresa', 4, 1.46, 'Sabor miel, textura crujiente.'),
('Galleta de Miel', 3, 2.01, 'Sabor canela, textura crujiente.'),
('Galleta de Jengibre', 7, 2.98, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Coco', 6, 3.15, 'Sabor fresa, textura suave.'),
('Galleta de Coco', 4, 2.29, 'Sabor avena, textura crujiente.'),
('Galleta de Vainilla', 1, 4.57, 'Sabor avena, textura crujiente.'),
('Galleta de Coco', 4, 3.86, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Caramelo', 5, 4.95, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 8, 1.89, 'Sabor caramelo, textura crujiente.'),
('Galleta de Canela', 1, 1.23, 'Sabor avena, textura crujiente.'),
('Galleta de Fresa', 10, 3.04, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 8, 4.41, 'Sabor miel, textura crujiente.'),
('Galleta de Chocolate', 10, 4.69, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Chocolate', 2, 2.24, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 2, 2.86, 'Sabor avena, textura crujiente.'),
('Galleta de Mantequilla', 2, 1.08, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 4, 2.74, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 6, 4.69, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Jengibre', 8, 2.86, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 4, 4.27, 'Sabor avena, textura crujiente.'),
('Galleta de Mantequilla', 6, 2.01, 'Sabor coco, textura crujiente.'),
('Galleta de Naranja', 5, 1.9, 'Sabor fresa, textura suave.'),
('Galleta de Vainilla', 9, 1.4, 'Sabor chocolate, textura crujiente.'),
('Galleta de Fresa', 7, 1.04, 'Sabor miel, textura crujiente.'),
('Galleta de Coco', 9, 2.85, 'Sabor canela, textura crujiente.'),
('Galleta de Caramelo', 7, 2.13, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Fresa', 1, 2.46, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 10, 3.48, 'Sabor canela, textura crujiente.'),
('Galleta de Chocolate', 5, 3.55, 'Sabor naranja, textura crujiente.'),
('Galleta de Avena', 5, 1.52, 'Sabor caramelo, textura crujiente.'),
('Galleta de Jengibre', 8, 3.78, 'Sabor miel, textura crujiente.'),
('Galleta de Naranja', 9, 4.2, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Canela', 10, 2.42, 'Sabor coco, textura crujiente.'),
('Galleta de Caramelo', 10, 4.86, 'Sabor naranja, textura crujiente.'),
('Galleta de Miel', 10, 4.83, 'Sabor miel, textura crujiente.'),
('Galleta de Jengibre', 10, 2.81, 'Sabor jengibre, textura crujiente.'),
('Galleta de Vainilla', 10, 1.53, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Chocolate', 3, 3.06, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Coco', 9, 4.16, 'Sabor chocolate, textura crujiente.'),
('Galleta de Vainilla', 6, 3.85, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Vainilla', 8, 3.0, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 10, 2.64, 'Sabor canela, textura crujiente.'),
('Galleta de Vainilla', 7, 1.39, 'Sabor naranja, textura crujiente.'),
('Galleta de Naranja', 10, 4.26, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Avena', 7, 4.89, 'Sabor chocolate, textura crujiente.'),
('Galleta de Chocolate', 6, 2.18, 'Sabor caramelo, textura crujiente.'),
('Galleta de Naranja', 1, 4.73, 'Sabor caramelo, textura crujiente.'),
('Galleta de Coco', 6, 1.41, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 5, 2.04, 'Sabor jengibre, textura crujiente.'),
('Galleta de Miel', 6, 3.97, 'Sabor canela, textura crujiente.'),
('Galleta de Caramelo', 10, 2.56, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Naranja', 3, 1.61, 'Sabor caramelo, textura crujiente.'),
('Galleta de Fresa', 9, 4.39, 'Sabor miel, textura crujiente.'),
('Galleta de Canela', 5, 1.15, 'Sabor avena, textura crujiente.'),
('Galleta de Canela', 1, 1.52, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Vainilla', 4, 3.22, 'Sabor naranja, textura crujiente.'),
('Galleta de Coco', 1, 4.06, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 1, 2.95, 'Sabor fresa, textura suave.'),
('Galleta de Doble Chocolate', 1, 3.73, 'Sabor avena, textura crujiente.'),
('Galleta de Chocolate', 7, 1.85, 'Sabor coco, textura crujiente.'),
('Galleta de Vainilla', 4, 4.44, 'Sabor avena, textura crujiente.'),
('Galleta de Fresa', 9, 2.72, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 1, 2.73, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 7, 2.97, 'Sabor canela, textura crujiente.'),
('Galleta de Fresa', 2, 4.8, 'Sabor coco, textura crujiente.'),
('Galleta de Doble Chocolate', 5, 2.46, 'Sabor miel, textura crujiente.'),
('Galleta de Mantequilla', 2, 2.63, 'Sabor fresa, textura suave.'),
('Galleta de Fresa', 6, 3.69, 'Sabor canela, textura crujiente.'),
('Galleta de Caramelo', 3, 1.06, 'Sabor jengibre, textura crujiente.'),
('Galleta de Chocolate', 7, 2.82, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Coco', 7, 3.59, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Miel', 2, 2.26, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Jengibre', 4, 2.53, 'Sabor coco, textura crujiente.'),
('Galleta de Caramelo', 9, 2.07, 'Sabor canela, textura crujiente.'),
('Galleta de Coco', 10, 2.01, 'Sabor naranja, textura crujiente.'),
('Galleta de Caramelo', 10, 2.14, 'Sabor miel, textura crujiente.'),
('Galleta de Canela', 9, 4.07, 'Sabor chocolate, textura crujiente.'),
('Galleta de Coco', 8, 1.02, 'Sabor miel, textura crujiente.'),
('Galleta de Coco', 2, 3.74, 'Sabor avena, textura crujiente.'),
('Galleta de Fresa', 10, 3.56, 'Sabor jengibre, textura crujiente.'),
('Galleta de Fresa', 7, 2.49, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Caramelo', 1, 3.17, 'Sabor chocolate, textura crujiente.'),
('Galleta de Fresa', 2, 2.33, 'Sabor naranja, textura crujiente.'),
('Galleta de Fresa', 1, 4.22, 'Sabor avena, textura crujiente.'),
('Galleta de Avena', 9, 3.06, 'Sabor fresa, textura suave.'),
('Galleta de Canela', 10, 3.5, 'Sabor fresa, textura suave.'),
('Galleta de Doble Chocolate', 6, 3.32, 'Sabor naranja, textura crujiente.'),
('Galleta de Chocolate', 9, 2.6, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Avena', 4, 4.61, 'Sabor jengibre, textura crujiente.'),
('Galleta de Caramelo', 6, 4.62, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Miel', 6, 3.2, 'Sabor chocolate, textura crujiente.'),
('Galleta de Doble Chocolate', 10, 2.82, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Coco', 10, 2.37, 'Sabor caramelo, textura crujiente.'),
('Galleta de Jengibre', 3, 5.0, 'Sabor chocolate, textura crujiente.'),
('Galleta de Mantequilla', 8, 4.33, 'Sabor caramelo, textura crujiente.'),
('Galleta de Mantequilla', 5, 1.19, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 7, 3.91, 'Sabor miel, textura crujiente.'),
('Galleta de Fresa', 7, 3.88, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Doble Chocolate', 8, 1.29, 'Sabor avena, textura crujiente.'),
('Galleta de Miel', 2, 4.53, 'Sabor fresa, textura suave.'),
('Galleta de Doble Chocolate', 10, 1.53, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Jengibre', 8, 2.72, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Vainilla', 5, 2.96, 'Sabor chocolate, textura crujiente.'),
('Galleta de Vainilla', 1, 1.53, 'Sabor avena, textura crujiente.'),
('Galleta de Naranja', 7, 2.69, 'Sabor fresa, textura suave.'),
('Galleta de Chocolate', 5, 3.02, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Naranja', 3, 2.7, 'Sabor caramelo, textura crujiente.'),
('Galleta de Vainilla', 10, 1.6, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Caramelo', 3, 1.15, 'Sabor caramelo, textura crujiente.'),
('Galleta de Caramelo', 7, 4.31, 'Sabor miel, textura crujiente.'),
('Galleta de Coco', 8, 4.16, 'Sabor canela, textura crujiente.'),
('Galleta de Chocolate', 5, 2.26, 'Sabor caramelo, textura crujiente.'),
('Galleta de Coco', 2, 4.23, 'Sabor mantequilla, textura crujiente.'),
('Galleta de Miel', 6, 1.32, 'Sabor caramelo, textura crujiente.'),
('Galleta de Avena', 10, 2.4, 'Sabor jengibre, textura crujiente.'),
('Galleta de Naranja', 9, 4.55, 'Sabor doble chocolate, textura crujiente.'),
('Galleta de Caramelo', 7, 1.59, 'Sabor avena, textura crujiente.'),
('Galleta de Vainilla', 1, 3.78, 'Sabor chocolate, textura crujiente.'),
('Galleta de Coco', 4, 4.58, 'Sabor miel, textura crujiente.'),
('Galleta de Chocolate', 3, 1.64, 'Sabor fresa, textura suave.'),
('Galleta de Caramelo', 9, 4.13, 'Sabor canela, textura crujiente.'),
('Galleta de Chocolate', 8, 4.66, 'Sabor canela, textura crujiente.'),
('Galleta de Vainilla', 3, 1.51, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Fresa', 8, 1.68, 'Sabor naranja, textura crujiente.'),
('Galleta de Miel', 5, 2.63, 'Sabor chocolate, textura crujiente.'),
('Galleta de Naranja', 10, 4.88, 'Sabor vainilla, textura esponjosa.'),
('Galleta de Avena', 7, 2.19, 'Sabor doble chocolate, textura crujiente.');